

DALFormatError
=============================

.. currentmodule:: pyvo.dal.query

.. autoexception:: DALFormatError